## log and timestamp
SDK_TIMESTAMP_TEMPLATE_1=$(shell date +%Y%m%d%H%M%S)
SDK_BUILD_LOG=build-$(SDK_TIMESTAMP_TEMPLATE_1).log
SDK_ERROR_LOG=error-$(SDK_TIMESTAMP_TEMPLATE_1).log

## toolchain
ifeq ($(CONFIG_WITH_SYSTEM_CROSS_COMPILE),y)
CROSS_COMPILE_RV64=$(CONFIG_SYSTEM_CROSS_COMPILE)
endif

ifeq ($(CONFIG_WITH_EXTERNAL_CROSS_COMPILE),y)
CROSS_COMPILE_RV64=$(CONFIG_EXTERNAL_CROSS_COMPILE)
endif

CROSS_COMPILE_RV64_ENV=ARCH=riscv CROSS_COMPILE=$(CROSS_COMPILE_RV64)

ifeq ($(CONFIG_WITH_EXTERNAL_CROSS_COMPILE),y)
CROSS_COMPILE_RV64_ENV += PATH=$(CONFIG_EXTERNAL_CROSS_COMPILE_DIR):$${PATH}
endif


ifneq ($(BUILD_HOST), riscv)
	BUILD_RV64_ENV = $(CROSS_COMPILE_RV64_ENV)
else
	BUILD_RV64_ENV :=
endif

MAKE += -j$(BUILD_JOBS_N)
